FROM golang:alpine3.20

WORKDIR /app
COPY go.mod go.sum ./
COPY cmd/inventory/inventory.go ./

RUN go mod tidy
RUN CGO_ENABLED=0 GOOS=linux go build -o /inventory

ENV PORT=8081
EXPOSE 8081

CMD ["/inventory"]