apiVersion: apps/v1
kind: Deployment
metadata:
  name: goapp-deploy
spec:
  selector:
    matchLabels:
      app: goapp
  template:
    metadata:
      labels:
        app: goapp
    spec:
      containers:
      - name: goapp
        image: bikashpdash/goapp
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
  replicas: 2
